FurkannOzbek/application-hub

frontend/app/login/LogInForm.js
frontend/app/login/page.js
frontend/app/page.js
frontend/app/signup/SignUpForm.js
frontend/app/signup/page.js
frontend/app/user/page.js
frontend/components/fetches/useLogIn.js
frontend/components/fetches/useSignUp.js
frontend/components/styles/ThemeApp.js
frontend/components/ui/InputField.js

I implemented Styles, Palette of colors, change dark mode / light mode
I created pages, forms and functions submitting Log In, Sign Up.
Now it doesn't work with backend.

implemented styles-colors, LogIn form, Sign up form

---

.github/pull_request_template.md

- Implement a standard Pull Request template for consistent documentation
- Template includes sections for PR title, description, changes made, screenshots, testing steps, issues addressed, and additional notes
- This will improve project management and increase overall code quality

chore: add PR template for better project documentation

---

frontend/app/login/LogInForm.js
frontend/app/register/SignUpForm.js
frontend/app/register/page.js
frontend/app/user/page.js
frontend/components/fetches/useLogIn.js
frontend/components/fetches/useSignUp.js
frontend/components/ui/InputField.js

It was fixed Registration and login functionality, connected with Backend and Database, testing register and login of user.
Minor changed in Password Input.
---
List the main changes in this pull request. Describe what was added, modified, or removed.
- **Frontend:** Describe changes in the React components, hooks, or UI updates.
1. Rename folder from app/signup to app/register:
2. Update function useSignUp.js and useLogIn.js;
3. Fixed Password Input for correct display.
---
Video about registration and login 
https://github.com/user-attachments/assets/e1ae61f7-3da0-4ed3-97f6-a4b0a2bbd42b
---
Describe how to test this feature or bug fix.
1. **Frontend:** Testing for appering correct error massage. Need to wait for fixing from BackEnder

Fixing function of registration and minor changed in code

---

api/package-lock.json
api/package.json
frontend/package-lock.json
frontend/package.json

- Update Node and NPM versions in both api and frontend package.json for compatibility with new packages
- Enforce engineStrict in package.json to ensure correct versions are used
- Add react, react-dom, and next as peer dependencies in frontend/package.json to maintain version consistency

chore: update Node, NPM versions and add peer dependencies

---

.githooks/pre-commit
README.md
api/eslint.config.js
api/package-lock.json
api/package.json
frontend/package-lock.json
frontend/package.json

- Improve the efficiency of the pre-commit hook by only tracking and modifying necessary files.
- Enhance control over files to be linted through ESLint configuration updates.
- Keep development environment up-to-date and efficient with the latest devDependencies.
- Modified pre-commit hook to track staged files before running lint/format and abort if any of the staged files were modified during this process.
- Updated ESLint configuration to include file extensions for more precise linting.
- Upgraded devDependencies in both API and frontend packages to their latest versions. Also added a note in the README about using two separate VS Code windows for simultaneous frontend and backend work.
- More efficient pre-commit operations, ensuring only necessary files are tracked and modified.

Pks chore upgrade dev dependencies in api and frontend packages

---

.editorconfig
.gitattributes

- Ensure consistent coding styles across various editors and IDEs.
- Handle line endings normalization and binary files declaration in the version control system.
- Added .editorconfig file for maintaining coding style consistency.
- Introduced .gitattributes file for line endings normalization and binary files management.
- Uniform coding style in the project, irrespective of the editor used.
- Proper handling of line endings and binary files in Git, reducing issues related to cross-platform development.

chore: Add .editorconfig and .gitattributes for Consistent Coding and Version Control

---

frontend/app/layout.js
frontend/components/ui/NavBar.js

Implemented toggle Icon for dark mode, light mode.
---
change the button for login and signUp

Implemented light mode dark mode in NavBar

---

api/.husky/pre-commit
api/package-lock.json
api/package.json
frontend/.husky/pre-commit
frontend/package-lock.json
frontend/package.json

[CHORE] Remove Husky 
---
Removes Husky as we're now using custom git hooks for pre-commit linting and formatting functionality.
- Problem: Git hooks configuration with Husky
- Impact: Simplified development setup  and reduced dependencies
---
Removed all Husky-related configurations and dependencies from both project folders:
- Removed Files/Folders: 
- Deleted .husky/ directory and its contents
- Package.json Changes:
- Removed husky from dependencies
- Removed any Husky-related configurations
-Dependencies:
- Uninstalled Husky package (npm uninstall husky)
---
1. Git Hooks Verification:
- Make a commit to verify that custom git hooks for linting and formatting are still working
- Ensure pre-commit checks are functioning as expected

[CHORE] Remove Husky 

---

api/src/controllers/userController.js
api/src/routers/login.js
api/src/routers/user.js

---
This PR addresses a bug in the login functionality and implements a new endpoint for the user applications.
- Fixes login functionality by correcting the table name reference from "users" to "user"
- Adds a new endpoint to fetch all user applications with company names for the dashboard
- Improves code organization by moving business logic to controllers
---
Backend:
1. Bug Fix:
- Modified login query to reference correct table name user instead of users
2. New Endpoint:
- Added GET /api/user/applications endpoint to fetch user's applications with company names
- Implemented left join with company table to ensure all applications are returned
3. Code Refactoring:
- Created userController.js to handle business logic
- Moved application retrieval logic from routes to controller
- …

[FIX/FEATURE] Fix Users Table Reference and Implement Applications Endpoint

---

.githooks/pre-commit
frontend/components/homepage/HomePage.js

* Very small typo mistake fixed

fix:small typo mistake fixed

---

frontend/components/styles/ThemeApp.js

---
Optimization code with common colors for Darm mode and Light mode 
```
const sharedColors = {
primary: { main: '#134B48' },
secondary: { main: '#BB8266' },
accent: { main: '#F4A261' },
paperCommon: { main: '#F7F7F7' },
dashboard: { main: '#C5D5D4' },
}
```
Add a new color   `dashboard: '#C5D5D4' `
---
- **Frontend:** UI updates with colors

Change and improve colors

---

frontend/app/hooks/useApplicationById.js
frontend/utils/api.js

---
1. Add a new fetch function `fetchApplicationById` to api.js
2. Create a function for getting the application by id
---
- **Frontend:** 
- Update api.js
- Create useApplicationById.js

[FEATURE] Get application by id

---

frontend/app/user/applications/[id]/CustomDrawer.js
frontend/app/user/applications/[id]/DashboardApplicationHeader.js
frontend/app/user/applications/[id]/DashboardApplicationMain.js
frontend/app/user/applications/[id]/Documents.js
frontend/app/user/applications/[id]/Edit.js
frontend/app/user/applications/[id]/Interview.js
frontend/app/user/applications/[id]/Notes.js
frontend/app/user/applications/[id]/Overview.js
frontend/app/user/applications/[id]/page.js

---
1. Created Application Page
2. Implemented Overview side
3. Created layout, desktop/mobile version
P.S. 
1. This page does not have the fetch function. It will update after approving this PR: [](https://github.com/FurkannOzbek/application-hub/pull/27)
2. Code about to get data was commented
---
- **Frontend:** 
1. CustomDrawer.js;
2. DashboardApplicationHeader.js
3. DashboardApplicationMain.js
4. Overview.js
The components will be implemented later: Interview.js, Notes.js, Documents.js, Notes.js
---

Create application page (UI)

---

frontend/package-lock.json
frontend/package.json

Install @mui-lab

---

frontend/app/user/MotivationalQuote.js
frontend/app/user/SearchField.js
frontend/app/user/applications/ApplicationsBoard.js
frontend/app/user/applications/EmptyState.js
frontend/app/user/page.js
frontend/package-lock.json
frontend/package.json

---
Added search functionality to filter job applications by company name and job title, improving user experience by allowing quick access to specific applications. The implementation includes real-time filtering with a debounced search and an empty state display for no results.
- Problem: Users needed a way to quickly find specific job applications
- Impact: Improved application accessibility and user efficiency in managing multiple job applications
---
Frontend:
1. Search Implementation:
- Added debounced search using `react-use` library
- Implemented filtering logic for company names and job titles
- Case-insensitive search with whitespace handling
2. Components:
- Modified SearchField component to handle search input
- Added EmptyState component for both no applications and no search …

[FEATURE] Implement Search Functionality for Job Applications

---

api/src/controllers/userController.js
api/src/index.js
api/src/routers/login.js
api/src/routers/register.js
api/src/utils/getOrCreateCompanyId.js

- New console.errors added to be helpfull to backend developers
- Case-insensitive company name compare logic added
Logging for errors was missing in some of the API calls, and these improvements help backend developers better understand the mistakes by logging the errors in the console.
---
- **Frontend:** Describe changes in the React components, hooks, or UI updates.
- **Backend:**  Added some console.errors , and updated company name compare logic to be case-insensitive
---

fix: Better error handling and some changes on getOrCreateCompany

---

frontend/app/user/ApplicationAddForm.js

---
This PR improves the user experience of the Application Add Form by implementing responsive design patterns and refining the UI elements across different screen sizes.
- Enhances form usability on mobile devices
- Improves visual consistency and spacing
- Updates form field labels for better clarity
---
Frontend Updates:
- Added responsive width adjustments for modal containers using MUI breakpoints
- Implemented responsive typography scaling for different screen sizes
- Enhanced form layout with improved spacing and alignment
- Modified field labels to be more concise and clear:
- "Job Link (Optional)" → "Job Link"
- "Application Date (Optional)" → "Application Date"
- "Deadline Date (Optional)" → "Deadline Date"
- "Job Description (Optional)" → "Job Description"
- Updated modal …

[FIX] Enhance Add Application Form Responsiveness and Layout

---

frontend/app/layout.js
frontend/app/login/LogInForm.js
frontend/app/register/SignUpForm.js
frontend/components/ProtectedRoute.js
frontend/components/ui/NavBar.js

---
Minor typo fixed on a file name 
---
- **Frontend:**  Typo Correction
- **Backend:**  -
---

fix: minor typo correction for deployment fail

---

api/src/controllers/userController.js
api/src/routers/user.js
api/src/utils/getApplicationById.js
api/src/utils/getCompanyById.js
api/src/utils/updateField.js

[FEATURE] Add Endpoint to Update User Application and Company Details
---
This pull request introduces a new feature to update user applications and associated company details in the database. The goal is to provide users with the ability to edit application information (e.g., job title, status, salary) and update or associate company data (e.g., company name, website, location).
- **Impact:** Enhances user experience by allowing modifications to application records and maintains data consistency between applications and companies.
---
- **Added:** 
- `patchUserApplicationAndCompany` controller in `userController.js`:
- Updates application fields (e.g., job title, status, salary).
- Updates or associates company fields using a helper function `getOrCreateCompanyId`.
- New utility function …

[FEATURE] Add Endpoint to Update User Application and Company Details

---

api/src/controllers/userController.js
api/src/routers/user.js

**[FEATURE] Implement Deletion of User Applications**
---
This pull request introduces the functionality to delete user applications by their unique ID.
- **Problem solved:** Users were previously unable to remove applications they no longer needed.
- **Impact:** Enhances user experience by allowing them to manage their application data more effectively.
---
1. **New API Endpoint**: Added a `DELETE /applications/:id` endpoint.
- **Controller**: Created a `deleteUserApplicationsById` function in `userController.js`.
- **Router**: Added the new route in `user.js` and connected it to the controller.
2. **Validation**:
- Checks for valid application IDs.
- Ensures the application belongs to the user making the request.
3. **Database Interaction**:
- Retrieves the application for validation.
- …

[FEATURE] Implement Deletion of User Applications

---

api/src/routers/refreshToken.js

---
This PR improves the error handling in the token refresh endpoint by implementing more specific error cases and appropriate HTTP status codes.
- Problem: The current implementation uses a single try/catch block that catches all errors indiscriminately and returns 500 status codes for all errors, which is not ideal for operational monitoring and client feedback.
- Impact: Better error handling leads to improved debugging, and more accurate client feedback.
---
- Split single try/catch block into separate blocks for token verification and database operations
- Implemented specific error handling for different JWT verification scenarios
- Reserved 500 status codes exclusively for actual server-side errors
- Added more descriptive error messages for different failure scenarios
---
Backend …

[REFACTOR] Improve Error Handling in Token Refresh Endpoint

---

frontend/app/loading.js

---
Added a centralized loading component to provide visual feedback during data fetching and page transitions throughout the application.
- Problem: Users had no visual indication of loading states
- Impact: Improves user experience by providing clear feedback when the application is processing
---
Frontend:
- Created new loading.js page component using Next.js loading convention
- Implemented a centred circular progress indicator using Material-UI
---
---
- Navigate between different pages to see the loading state
- Verify the loading spinner is centered on the page
- Confirm the loading indicator matches the application's theme
- Test on different screen sizes to ensure proper responsiveness
---
Closes [Create Loading page](https://trello.com/c/43drja8F)

[FEATURE] Add Loading Component for Better User Experience

---

README.md
api/.env.example
api/src/config.js
api/src/index.js

- Enhance the handling of .env variables for improved efficiency and maintainability.
- Better organization of code to ensure .env file is loaded prior to any operation.
- Removed redundant DATABASE_URL from .env. Database related variables are now set individually.
- Moved 'dotenv/config' import to config.js, ensuring .env file is loaded before any operation is performed.
- Resulted in improved code organization and maintainability.
- More efficient handling of environment variables
- Enhanced code maintainability with a better code organization strategy.

Refactor: Optimize .env Variables Handling and Improve Code Organization

---

frontend/app/applications/[id]/page.js
frontend/components/ui/Notification.js

- Improve application performance by optimizing the rendering process.
- Align with best practices for React development.
- Moved Notification component outside of Content to prevent unnecessary re-rendering when useNotification hook triggers a state change.
- The changes were guided by the best practices from the Advanced React Book by Nadia Makarevich.
- Improved application performance due to more efficient rendering.
- Adherence to React's best practices for a more maintainable codebase.

refactor: move Notification component for optimizing rendering

---

frontend/app/applications/[id]/forms/ApplicationEditForm.js
frontend/app/applications/[id]/forms/CompanyEditForm.js
frontend/app/applications/[id]/page.js
frontend/app/login/LogInForm.js
frontend/app/register/SignUpForm.js

- Enhance performance and user experience by reducing unnecessary re-renders in form components.
- Improve loading state handling for better user feedback during form submission.
- Refactored useForm hook in ApplicationEditForm, CompanyEditForm, LogInForm, and SignUpForm components to avoid unnecessary re-renders.
- Removed `watch()` from useForm hook to prevent unintended sibling form control re-renders.
- Updated form submission handlers to accept updatedData, contactData, and userData as arguments, removing the need for `watch()`.
- Improved performance and user experience due to reduced re-renders in form components.

refactor: optimize useForm hook usage to avoid unnecessary re-renders

---

frontend/app/user/MotivationalQuote.js
frontend/utils/api.js

---
This PR implements a more robust and consistent approach to API request handling and error management across the application.
- Centralizes API request logic with a new apiRequest utility function
- Improves error handling with standardized error states
- Simplifies the motivational quote component with better state management
---
- API Utilities (frontend/utils/api.js):
- Implement a utility function to construct absolute URLs dynamically based on the environment's base URL 
- Implement a new apiRequest utility function for centralized request handling
- Standardized error handling across all API endpoints
- Simplified API endpoint implementations using the new utility
- Motivational Quote Component (frontend/app/user/MotivationalQuote.js):
- Refactored state management for better …

[REFACTOR] Improve API Request Handling and Error Management

---

frontend/app/layout.js
frontend/app/loading.js
frontend/components/Context/Authentication.js
frontend/components/RouteGuard.js
frontend/components/ui/Loader.js

---
This PR implements route protection. It ensures that authenticated users are properly redirected to appropriate pages and adds loading states during authentication checks.
- Problem: The application needed proper route protection to control access to public routes
- Impact: Enhanced security and better user experience with proper redirects and loading states
---
- Added new `RouteGuard` component to handle route protection logic
- Restructured the application layout for better authentication flow
- New Components:
- Created `RouteGuard` component for handling route protection
- Added reusable `Loader` component for consistent loading states
- Modified Components:
- Updated `AuthProvider` to expose loading state
- Simplified `loading.js` to use the new `Loader` component
- Restructured …

[FEATURE] Implement Route Protection for Authenticated Users

---

api/src/controllers/userCompanyContactsController.js
api/src/routers/user.js
api/src/utils/getCompanyContactId.js

---
This pull request introduces the functionality to manage company contacts for a specific application. It includes APIs to:
- Update an existing contact.
- Delete a contact.
This feature solves the need for an API to manage company contacts, including updating and deleting contacts associated with a company and application.
- It allows users to interact with company contacts programmatically, which enhances the management and organization of contact information within applications.
- It provides a set of API endpoints for CRUD operations on company contacts.
---
- **Controllers:** 
- Added functions for handling the updating and deletion of company contacts (`patchCompanyContact`, `deleteCompanyContact`).
- Implemented error handling, including checks for required fields and validation …

[FEATURE] Implement PATCH, DELETE Company Contact Management

---

api/src/dtos/errorDto.js
api/src/routers/login.js
frontend/utils/api.js

---
This PR introduces a standardized error handling system across the application to ensure consistent error responses between the backend and frontend.
Problems Solved:
- Inconsistent error response formats across different endpoints
- Lack of standardized error handling in API requests
- Difficulty in debugging due to varying error structures
Impact:
- Improved error handling consistency
- Better developer experience
- Cleaner code through standardization
---
1. New Error DTO Implementation
2. Login Endpoint Update:
- Refactored error responses to use the new DTO
- Improved error messages and status codes
- Added detailed error information where applicable
1. API Request Handler Update:
- Modified error handling to work with the new error format
---
---
1. Login Endpoint:
- Test with …

[REFACTOR] Implement Standardized Error Handling

---

frontend/components/ui/Footer.js
frontend/components/ui/Logo.js

1.  Removes the item prop from the Grid.
2. made correction in the width by adding px

removed the item prop from grid

---

api/src/controllers/noteController.js
api/src/controllers/publicApiController.js
api/src/controllers/userCompanyContactsController.js
api/src/controllers/userController.js
api/src/index.js
api/src/middleware/tokenAuthentication.js
api/src/routers/logout.js
api/src/routers/refreshToken.js
api/src/routers/register.js
frontend/utils/api.js

---
Provide a brief summary of what this PR does. Include context, objectives, and any other relevant information.
- What problem does this PR solve?
- What is the impact of the change?
---
- Implemented consistent error format: `{ status: 'error', message: string, details: { cause?: string } }`
- Updated error handling in controllers:
- `noteController.js`
- `userController.js`
- `userCompanyContactsController.js`
- `publicApiController.js`
- Enhanced middleware error handling (`tokenAuthentication.js`)
- Added sanitization for note content
- Updated `apiRequest` utility to handle standardized error responses
- Simplified error handling in API calls
---
1. Error Response Format
- Test API endpoints with invalid inputs
- Verify error responses follow the new format
- Check error details …

[REFACTOR] Standardize Error Handling and Response Format

---

api/src/controllers/noteController.js
frontend/app/applications/[id]/tabs/Notes.js
frontend/components/Context/NotificationContext.js
frontend/components/ui/Notification.js

#[REFACTOR] Improve Note Management UX
---
This pull request enhances the user experience for managing notes within the application. It introduces improved feedback mechanisms and integrates a consistent notification system across components.
- Problem: Previously, users experienced poor feedback when attempting to save empty notes or delete notes. Also, user access to a specific note was not verified. 
- Impact: The changes provide users with immediate and clear feedback, prevent accidental data loss, and improve overall interaction with note management features.
Also they ensure that notes are only created, updated, or deleted if the application exists for the user, preventing unauthorised access.
---
- Notes Component:
- Integrated DeleteModal to replace the previous modal logic, …

#[REFACTOR] Improve Note Management UX

---

api/src/controllers/userCompanyContactsController.js
frontend/app/applications/[id]/forms/ContactForm.js
frontend/app/applications/[id]/tabs/Contacts.js

---
This PR focuses on improving the contact update functionality by implementing proper response handling in the backend and optimizing the state update logic in the frontend. The changes ensure that contact updates are properly tracked and reflected in the UI.
- Implements proper response handling for contact updates
- Returns complete contact data after updates
- Optimizes frontend state management with immutable updates
---
1. Backend (`patchCompanyContact`)
- Enhanced update operation to return complete contact information using .returning()
- Added validation to check if contact exists after update
- Improved response structure by returning specific contact fields
2. Frontend (`Contacts.js`)
- Refactored `handleContactEdited` to use functional state updates
- Improved contact update …

[FIX] Enhance Contact Update Logic 

---

frontend/package-lock.json
frontend/package.json
package-lock.json

This PR install `sharp` to handle image optimizations.

[FIX] install sharp

---

frontend/app/applications/[id]/tabs/Notes.js
frontend/components/ui/RichTextEditor.js

---
This pull request addresses a bug in the RichTextEditor component where the cursor would unexpectedly jump during text editing. Additionally, it enhances the user interface by improving the appearance of the save button in the Notes component. The aim is to provide a smoother text editing experience and a more interactive UI for users.
•	Problem Solved: The cursor jumping issue disrupted the user's text input flow, and the save button lacked interactive feedback during the saving process.
•	Impact of the Change: These changes ensure a stable and reliable text editing environment and provide users with visual feedback during save operations, enhancing the overall user experience.
---
- RichTextEditor Component:
▪	Improved the DOM sanitization process to prevent unnecessary updates that …

[ENHANCEMENT] Improve Notes and RichTextEditor Components

---

frontend/app/applications/[id]/forms/ApplicationEditForm.js
frontend/app/applications/[id]/forms/CompanyEditForm.js
frontend/app/applications/[id]/forms/InterviewForm.js
frontend/app/applications/add/ApplicationAddForm.js
frontend/components/ui/InputField.js
frontend/utils/validators.js

---
This pull request introduces consistent URL validation across multiple forms in the application. The change centralizes the validation logic into a single utility function, reducing redundancy and ensuring uniform behavior. This helps improve code maintainability and user experience.
- **Problem:** URL validation logic was previously duplicated across components.
- **Solution:** Created a reusable `isValidURL` function in the `utils/validators.js` file and integrated it into relevant forms.
---
1. **Forms:**
- Added URL validation using `isValidURL` to the following components:
- `ApplicationEditForm.js`
- `CompanyEditForm.js`
- `InterviewForm.js`
- `ApplicationAddForm.js`
- Removed inline URL validation logic from `InterviewForm.js`.
2. **UI Components:**
- Updated `InputField.js` to …

[FEATURE] Add URL Validation Across Forms

---

frontend/app/applications/[id]/forms/ContactForm.js
frontend/next.config.mjs
frontend/package-lock.json
frontend/package.json

[IMPROVEMENT] Implement Phone Input with MUI Tel Input Library
---
This pull request integrates the MUI Tel input library into the project to provide additional features like country flag display and number formatting. This allows users to select their country code and automatically formats the phone number input accordingly.
---
List the main changes in this pull request. Describe what was added, modified, or removed.
- **Frontend:**
- Integrated MUI Tel input library into the phone number input field.
- Added flag selection and phone number formatting based on the selected country.
- Updated React components to utilize the new phone input field, ensuring compatibility with the rest of the form.
- **Backend:** N/A
---
---
Describe how to test this feature or bug fix.
1. **Frontend:** 
- …

[IMPROVEMENT] Phone Input Validation Change

---

frontend/app/applications/[id]/forms/ContactForm.js

[IMPROVEMENT] Implement Email Validation in Contacts Tab
---
This pull request adds email validation to the contacts tab. It ensures that any email entered in the contact form is in a valid format before submission. This enhances data quality and prevents users from submitting incorrect email addresses.
---
- Frontend:
- Implemented email validation in the contacts form.
- Added real-time feedback to the user when an invalid email is entered.
- Updated the UI to display an error message if the email format is incorrect.
---
---
- Frontend:
- Go to the contacts tab.
- Try adding an invalid email (e.g., invalidemail.com) and check that an error message is displayed.
- Enter a valid email (e.g., contact@example.com) and ensure that the form allows submission without errors.
---

[IMPROVEMENT] Implement Email Validation in Contacts Tab

---

api/src/middleware/tokenAuthentication.js

---
This pull request enhances the error handling in the verifyAuthToken middleware function used for JWT authentication. The improvements aim to provide more accurate feedback to clients by distinguishing between token-related errors and database-related issues.
- Problem Solved: Previously, the middleware did not differentiate between errors caused by invalid or expired tokens and those arising from database operations. This could lead to misleading error messages for users and make debugging more challenging.
- Impact of the Change: Users will receive clearer error messages that specify whether an issue is due to token validation or a database error. This enhances user experience and aids in quicker troubleshooting.
---
- Implemented nested `try-catch` blocks to separately handle JWT …

[ENHANCEMENT] Improve Error Handling in JWT Authentication Middleware

---

frontend/app/applications/[id]/forms/ApplicationEditForm.js

This PR includes small fix about default value of job_link

fix: default value added to job_link input
